services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto_broker
    restart: always
    ports:
      - "1883:1883"  # MQTT Port
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log