persistence true
persistence_location /mosquitto/data/

log_dest stdout
<<<<<<< HEAD

# Standard MQTT Port
listener 1883

# Allow anonymous connections (Required for your current Python script)
allow_anonymous true
=======
listener 1883
allow_anonymous true
>>>>>>> 6e0192f4aafbea640eb2917f7e7f000450196013
