persistence true
persistence_location /mosquitto/data/

log_dest stdout

# Standard MQTT Port
listener 1883

# Allow anonymous connections (Required for your current Python script)
allow_anonymous true