apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: my-org
      defaultBucket: sensors
    secureJsonData:
      token: super-long-admin-token
