[env]
platform = espressif32
framework = arduino, espidf
monitor_speed = 115200
# Shared Libraries
lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.3
    adafruit/Adafruit LSM6DS @ ^4.7.0
    adafruit/Adafruit BusIO @ ^1.16.0
    adafruit/Adafruit Unified Sensor @ ^1.1.14
# Global workaround for the WiFi Macro bug
build_flags = 
    -D CONFIG_ESP32_WIFI_CACHE_TX_BUFFER_NUM=32

[env:esp32dev]
board = esp32dev
board_build.flash_size = 8MB
board_build.partitions = partitions.csv

# ----- S3 -----
[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1
upload_speed = 921600
lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.3
    adafruit/Adafruit LSM6DS @ ^4.7.0
    adafruit/Adafruit BusIO @ ^1.16.0
    adafruit/Adafruit Unified Sensor @ ^1.1.14

# --- PARTITIONING STRATEGY ---
# Force 4MB Flash Size
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
# Use custom A/B table
board_build.partitions = partitions_4mb_ota.csv

# --- BUILD FLAGS ---
build_flags = 
    ${env.build_flags}
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D CONFIG_ESPTOOLPY_FLASHSIZE_4MB=1